/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as MypageIndexRouteImport } from './routes/mypage/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as WorshipSongsIndexRouteImport } from './routes/worship/songs/index'
import { Route as WorshipSetlistsIndexRouteImport } from './routes/worship/setlists/index'
import { Route as WorshipSetlistsIdRouteImport } from './routes/worship/setlists/$id'
import { Route as WorshipSongsIdViewRouteImport } from './routes/worship/songs/$id.view'
import { Route as WorshipSetlistsIdViewRouteImport } from './routes/worship/setlists/$id.view'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageIndexRoute = MypageIndexRouteImport.update({
  id: '/mypage/',
  path: '/mypage/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorshipSongsIndexRoute = WorshipSongsIndexRouteImport.update({
  id: '/worship/songs/',
  path: '/worship/songs/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorshipSetlistsIndexRoute = WorshipSetlistsIndexRouteImport.update({
  id: '/worship/setlists/',
  path: '/worship/setlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorshipSetlistsIdRoute = WorshipSetlistsIdRouteImport.update({
  id: '/worship/setlists/$id',
  path: '/worship/setlists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorshipSongsIdViewRoute = WorshipSongsIdViewRouteImport.update({
  id: '/worship/songs/$id/view',
  path: '/worship/songs/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const WorshipSetlistsIdViewRoute = WorshipSetlistsIdViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => WorshipSetlistsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutRoute
  '/login/': typeof LoginIndexRoute
  '/mypage/': typeof MypageIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/worship/setlists/$id': typeof WorshipSetlistsIdRouteWithChildren
  '/worship/setlists/': typeof WorshipSetlistsIndexRoute
  '/worship/songs/': typeof WorshipSongsIndexRoute
  '/worship/setlists/$id/view': typeof WorshipSetlistsIdViewRoute
  '/worship/songs/$id/view': typeof WorshipSongsIdViewRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutRoute
  '/login': typeof LoginIndexRoute
  '/mypage': typeof MypageIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/worship/setlists/$id': typeof WorshipSetlistsIdRouteWithChildren
  '/worship/setlists': typeof WorshipSetlistsIndexRoute
  '/worship/songs': typeof WorshipSongsIndexRoute
  '/worship/setlists/$id/view': typeof WorshipSetlistsIdViewRoute
  '/worship/songs/$id/view': typeof WorshipSongsIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRoute
  '/login/': typeof LoginIndexRoute
  '/mypage/': typeof MypageIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/worship/setlists/$id': typeof WorshipSetlistsIdRouteWithChildren
  '/worship/setlists/': typeof WorshipSetlistsIndexRoute
  '/worship/songs/': typeof WorshipSongsIndexRoute
  '/worship/setlists/$id/view': typeof WorshipSetlistsIdViewRoute
  '/worship/songs/$id/view': typeof WorshipSongsIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/mypage/'
    | '/onboarding/'
    | '/schedule/'
    | '/worship/setlists/$id'
    | '/worship/setlists/'
    | '/worship/songs/'
    | '/worship/setlists/$id/view'
    | '/worship/songs/$id/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mypage'
    | '/onboarding'
    | '/schedule'
    | '/worship/setlists/$id'
    | '/worship/setlists'
    | '/worship/songs'
    | '/worship/setlists/$id/view'
    | '/worship/songs/$id/view'
  id:
    | '__root__'
    | '/_layout'
    | '/login/'
    | '/mypage/'
    | '/onboarding/'
    | '/schedule/'
    | '/worship/setlists/$id'
    | '/worship/setlists/'
    | '/worship/songs/'
    | '/worship/setlists/$id/view'
    | '/worship/songs/$id/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MypageIndexRoute: typeof MypageIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  WorshipSetlistsIdRoute: typeof WorshipSetlistsIdRouteWithChildren
  WorshipSetlistsIndexRoute: typeof WorshipSetlistsIndexRoute
  WorshipSongsIndexRoute: typeof WorshipSongsIndexRoute
  WorshipSongsIdViewRoute: typeof WorshipSongsIdViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/': {
      id: '/mypage/'
      path: '/mypage'
      fullPath: '/mypage/'
      preLoaderRoute: typeof MypageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worship/songs/': {
      id: '/worship/songs/'
      path: '/worship/songs'
      fullPath: '/worship/songs/'
      preLoaderRoute: typeof WorshipSongsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worship/setlists/': {
      id: '/worship/setlists/'
      path: '/worship/setlists'
      fullPath: '/worship/setlists/'
      preLoaderRoute: typeof WorshipSetlistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worship/setlists/$id': {
      id: '/worship/setlists/$id'
      path: '/worship/setlists/$id'
      fullPath: '/worship/setlists/$id'
      preLoaderRoute: typeof WorshipSetlistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worship/songs/$id/view': {
      id: '/worship/songs/$id/view'
      path: '/worship/songs/$id/view'
      fullPath: '/worship/songs/$id/view'
      preLoaderRoute: typeof WorshipSongsIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worship/setlists/$id/view': {
      id: '/worship/setlists/$id/view'
      path: '/view'
      fullPath: '/worship/setlists/$id/view'
      preLoaderRoute: typeof WorshipSetlistsIdViewRouteImport
      parentRoute: typeof WorshipSetlistsIdRoute
    }
  }
}

interface WorshipSetlistsIdRouteChildren {
  WorshipSetlistsIdViewRoute: typeof WorshipSetlistsIdViewRoute
}

const WorshipSetlistsIdRouteChildren: WorshipSetlistsIdRouteChildren = {
  WorshipSetlistsIdViewRoute: WorshipSetlistsIdViewRoute,
}

const WorshipSetlistsIdRouteWithChildren =
  WorshipSetlistsIdRoute._addFileChildren(WorshipSetlistsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRoute,
  LoginIndexRoute: LoginIndexRoute,
  MypageIndexRoute: MypageIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  WorshipSetlistsIdRoute: WorshipSetlistsIdRouteWithChildren,
  WorshipSetlistsIndexRoute: WorshipSetlistsIndexRoute,
  WorshipSongsIndexRoute: WorshipSongsIndexRoute,
  WorshipSongsIdViewRoute: WorshipSongsIdViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
