/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as MyChurchIndexRouteImport } from './routes/my-church/index'
import { Route as MypageIndexRouteImport } from './routes/mypage/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as PlazaIndexRouteImport } from './routes/plaza/index'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as WorshipSetlistsIndexRouteImport } from './routes/worship/setlists/index'
import { Route as WorshipSongsIndexRouteImport } from './routes/worship/songs/index'
import { Route as WorshipSongsNewRouteImport } from './routes/worship/songs/new'
import { Route as WorshipSetlistsIdIndexRouteImport } from './routes/worship/setlists/$id/index'
import { Route as WorshipSetlistsIdViewRouteImport } from './routes/worship/setlists/$id/view'
import { Route as WorshipSongsIdEditRouteImport } from './routes/worship/songs/$id.edit'
import { Route as WorshipSongsIdViewRouteImport } from './routes/worship/songs/$id.view'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyChurchIndexRoute = MyChurchIndexRouteImport.update({
  id: '/my-church/',
  path: '/my-church/',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageIndexRoute = MypageIndexRouteImport.update({
  id: '/mypage/',
  path: '/mypage/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlazaIndexRoute = PlazaIndexRouteImport.update({
  id: '/plaza/',
  path: '/plaza/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorshipSetlistsIndexRoute = WorshipSetlistsIndexRouteImport.update({
  id: '/worship/setlists/',
  path: '/worship/setlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorshipSongsIndexRoute = WorshipSongsIndexRouteImport.update({
  id: '/worship/songs/',
  path: '/worship/songs/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorshipSongsNewRoute = WorshipSongsNewRouteImport.update({
  id: '/worship/songs/new',
  path: '/worship/songs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorshipSetlistsIdIndexRoute = WorshipSetlistsIdIndexRouteImport.update({
  id: '/worship/setlists/$id/',
  path: '/worship/setlists/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorshipSetlistsIdViewRoute = WorshipSetlistsIdViewRouteImport.update({
  id: '/worship/setlists/$id/view',
  path: '/worship/setlists/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const WorshipSongsIdEditRoute = WorshipSongsIdEditRouteImport.update({
  id: '/worship/songs/$id/edit',
  path: '/worship/songs/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const WorshipSongsIdViewRoute = WorshipSongsIdViewRouteImport.update({
  id: '/worship/songs/$id/view',
  path: '/worship/songs/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/login/': typeof LoginIndexRoute
  '/my-church/': typeof MyChurchIndexRoute
  '/mypage/': typeof MypageIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/plaza/': typeof PlazaIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/worship/songs/new': typeof WorshipSongsNewRoute
  '/worship/setlists/': typeof WorshipSetlistsIndexRoute
  '/worship/songs/': typeof WorshipSongsIndexRoute
  '/worship/setlists/$id/view': typeof WorshipSetlistsIdViewRoute
  '/worship/songs/$id/edit': typeof WorshipSongsIdEditRoute
  '/worship/songs/$id/view': typeof WorshipSongsIdViewRoute
  '/worship/setlists/$id/': typeof WorshipSetlistsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/login': typeof LoginIndexRoute
  '/my-church': typeof MyChurchIndexRoute
  '/mypage': typeof MypageIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/plaza': typeof PlazaIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/worship/songs/new': typeof WorshipSongsNewRoute
  '/worship/setlists': typeof WorshipSetlistsIndexRoute
  '/worship/songs': typeof WorshipSongsIndexRoute
  '/worship/setlists/$id/view': typeof WorshipSetlistsIdViewRoute
  '/worship/songs/$id/edit': typeof WorshipSongsIdEditRoute
  '/worship/songs/$id/view': typeof WorshipSongsIdViewRoute
  '/worship/setlists/$id': typeof WorshipSetlistsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/login/': typeof LoginIndexRoute
  '/my-church/': typeof MyChurchIndexRoute
  '/mypage/': typeof MypageIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/plaza/': typeof PlazaIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/worship/songs/new': typeof WorshipSongsNewRoute
  '/worship/setlists/': typeof WorshipSetlistsIndexRoute
  '/worship/songs/': typeof WorshipSongsIndexRoute
  '/worship/setlists/$id/view': typeof WorshipSetlistsIdViewRoute
  '/worship/songs/$id/edit': typeof WorshipSongsIdEditRoute
  '/worship/songs/$id/view': typeof WorshipSongsIdViewRoute
  '/worship/setlists/$id/': typeof WorshipSetlistsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/users'
    | '/login/'
    | '/my-church/'
    | '/mypage/'
    | '/onboarding/'
    | '/plaza/'
    | '/schedule/'
    | '/worship/songs/new'
    | '/worship/setlists/'
    | '/worship/songs/'
    | '/worship/setlists/$id/view'
    | '/worship/songs/$id/edit'
    | '/worship/songs/$id/view'
    | '/worship/setlists/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/users'
    | '/login'
    | '/my-church'
    | '/mypage'
    | '/onboarding'
    | '/plaza'
    | '/schedule'
    | '/worship/songs/new'
    | '/worship/setlists'
    | '/worship/songs'
    | '/worship/setlists/$id/view'
    | '/worship/songs/$id/edit'
    | '/worship/songs/$id/view'
    | '/worship/setlists/$id'
  id:
    | '__root__'
    | '/'
    | '/admin/users'
    | '/login/'
    | '/my-church/'
    | '/mypage/'
    | '/onboarding/'
    | '/plaza/'
    | '/schedule/'
    | '/worship/songs/new'
    | '/worship/setlists/'
    | '/worship/songs/'
    | '/worship/setlists/$id/view'
    | '/worship/songs/$id/edit'
    | '/worship/songs/$id/view'
    | '/worship/setlists/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminUsersRoute: typeof AdminUsersRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MyChurchIndexRoute: typeof MyChurchIndexRoute
  MypageIndexRoute: typeof MypageIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  PlazaIndexRoute: typeof PlazaIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  WorshipSongsNewRoute: typeof WorshipSongsNewRoute
  WorshipSetlistsIndexRoute: typeof WorshipSetlistsIndexRoute
  WorshipSongsIndexRoute: typeof WorshipSongsIndexRoute
  WorshipSetlistsIdViewRoute: typeof WorshipSetlistsIdViewRoute
  WorshipSongsIdEditRoute: typeof WorshipSongsIdEditRoute
  WorshipSongsIdViewRoute: typeof WorshipSongsIdViewRoute
  WorshipSetlistsIdIndexRoute: typeof WorshipSetlistsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-church/': {
      id: '/my-church/'
      path: '/my-church'
      fullPath: '/my-church/'
      preLoaderRoute: typeof MyChurchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/': {
      id: '/mypage/'
      path: '/mypage'
      fullPath: '/mypage/'
      preLoaderRoute: typeof MypageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plaza/': {
      id: '/plaza/'
      path: '/plaza'
      fullPath: '/plaza/'
      preLoaderRoute: typeof PlazaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worship/setlists/': {
      id: '/worship/setlists/'
      path: '/worship/setlists'
      fullPath: '/worship/setlists/'
      preLoaderRoute: typeof WorshipSetlistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worship/songs/': {
      id: '/worship/songs/'
      path: '/worship/songs'
      fullPath: '/worship/songs/'
      preLoaderRoute: typeof WorshipSongsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worship/songs/new': {
      id: '/worship/songs/new'
      path: '/worship/songs/new'
      fullPath: '/worship/songs/new'
      preLoaderRoute: typeof WorshipSongsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worship/setlists/$id/': {
      id: '/worship/setlists/$id/'
      path: '/worship/setlists/$id'
      fullPath: '/worship/setlists/$id/'
      preLoaderRoute: typeof WorshipSetlistsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worship/setlists/$id/view': {
      id: '/worship/setlists/$id/view'
      path: '/worship/setlists/$id/view'
      fullPath: '/worship/setlists/$id/view'
      preLoaderRoute: typeof WorshipSetlistsIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worship/songs/$id/edit': {
      id: '/worship/songs/$id/edit'
      path: '/worship/songs/$id/edit'
      fullPath: '/worship/songs/$id/edit'
      preLoaderRoute: typeof WorshipSongsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worship/songs/$id/view': {
      id: '/worship/songs/$id/view'
      path: '/worship/songs/$id/view'
      fullPath: '/worship/songs/$id/view'
      preLoaderRoute: typeof WorshipSongsIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminUsersRoute: AdminUsersRoute,
  LoginIndexRoute: LoginIndexRoute,
  MyChurchIndexRoute: MyChurchIndexRoute,
  MypageIndexRoute: MypageIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  PlazaIndexRoute: PlazaIndexRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  WorshipSongsNewRoute: WorshipSongsNewRoute,
  WorshipSetlistsIndexRoute: WorshipSetlistsIndexRoute,
  WorshipSongsIndexRoute: WorshipSongsIndexRoute,
  WorshipSetlistsIdViewRoute: WorshipSetlistsIdViewRoute,
  WorshipSongsIdEditRoute: WorshipSongsIdEditRoute,
  WorshipSongsIdViewRoute: WorshipSongsIdViewRoute,
  WorshipSetlistsIdIndexRoute: WorshipSetlistsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
