/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as SongsIndexRouteImport } from './routes/songs/index'
import { Route as SetlistsIndexRouteImport } from './routes/setlists/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as SetlistsIdRouteImport } from './routes/setlists/$id'
import { Route as SongsIdViewRouteImport } from './routes/songs/$id.view'
import { Route as SetlistsIdViewRouteImport } from './routes/setlists/$id.view'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsIndexRoute = SongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetlistsIndexRoute = SetlistsIndexRouteImport.update({
  id: '/setlists/',
  path: '/setlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetlistsIdRoute = SetlistsIdRouteImport.update({
  id: '/setlists/$id',
  path: '/setlists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsIdViewRoute = SongsIdViewRouteImport.update({
  id: '/songs/$id/view',
  path: '/songs/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const SetlistsIdViewRoute = SetlistsIdViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => SetlistsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutRoute
  '/setlists/$id': typeof SetlistsIdRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/setlists/': typeof SetlistsIndexRoute
  '/songs/': typeof SongsIndexRoute
  '/setlists/$id/view': typeof SetlistsIdViewRoute
  '/songs/$id/view': typeof SongsIdViewRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutRoute
  '/setlists/$id': typeof SetlistsIdRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/setlists': typeof SetlistsIndexRoute
  '/songs': typeof SongsIndexRoute
  '/setlists/$id/view': typeof SetlistsIdViewRoute
  '/songs/$id/view': typeof SongsIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRoute
  '/setlists/$id': typeof SetlistsIdRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/setlists/': typeof SetlistsIndexRoute
  '/songs/': typeof SongsIndexRoute
  '/setlists/$id/view': typeof SetlistsIdViewRoute
  '/songs/$id/view': typeof SongsIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setlists/$id'
    | '/login/'
    | '/setlists/'
    | '/songs/'
    | '/setlists/$id/view'
    | '/songs/$id/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setlists/$id'
    | '/login'
    | '/setlists'
    | '/songs'
    | '/setlists/$id/view'
    | '/songs/$id/view'
  id:
    | '__root__'
    | '/_layout'
    | '/setlists/$id'
    | '/login/'
    | '/setlists/'
    | '/songs/'
    | '/setlists/$id/view'
    | '/songs/$id/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRoute
  SetlistsIdRoute: typeof SetlistsIdRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  SetlistsIndexRoute: typeof SetlistsIndexRoute
  SongsIndexRoute: typeof SongsIndexRoute
  SongsIdViewRoute: typeof SongsIdViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/': {
      id: '/songs/'
      path: '/songs'
      fullPath: '/songs/'
      preLoaderRoute: typeof SongsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setlists/': {
      id: '/setlists/'
      path: '/setlists'
      fullPath: '/setlists/'
      preLoaderRoute: typeof SetlistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setlists/$id': {
      id: '/setlists/$id'
      path: '/setlists/$id'
      fullPath: '/setlists/$id'
      preLoaderRoute: typeof SetlistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$id/view': {
      id: '/songs/$id/view'
      path: '/songs/$id/view'
      fullPath: '/songs/$id/view'
      preLoaderRoute: typeof SongsIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setlists/$id/view': {
      id: '/setlists/$id/view'
      path: '/view'
      fullPath: '/setlists/$id/view'
      preLoaderRoute: typeof SetlistsIdViewRouteImport
      parentRoute: typeof SetlistsIdRoute
    }
  }
}

interface SetlistsIdRouteChildren {
  SetlistsIdViewRoute: typeof SetlistsIdViewRoute
}

const SetlistsIdRouteChildren: SetlistsIdRouteChildren = {
  SetlistsIdViewRoute: SetlistsIdViewRoute,
}

const SetlistsIdRouteWithChildren = SetlistsIdRoute._addFileChildren(
  SetlistsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRoute,
  SetlistsIdRoute: SetlistsIdRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  SetlistsIndexRoute: SetlistsIndexRoute,
  SongsIndexRoute: SongsIndexRoute,
  SongsIdViewRoute: SongsIdViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
